### ISSUE TITLE
Batocera save state manager doesn’t work, plus a couple ideas.

### ISSUE THREAD

**Issue by Teh-Ghost** [rg35xx-cfw/rg35xx-cfw.github.io#123]
Hello. While testing, I noticed that the batocera save state manager functionality doesn’t work. 

I also noticed a couple other areas that might be worth looking into.
- additional shader sets would be useful…for example, the scanlines one has vertical scanlines only
- The ability to launch retroarch to adjust settings might be useful (maybe via app game collection category)
- a file manager might be useful too
- Leverage the rg35xx+ menu button for a single press menu of common navigation items.

great work so far…seems stable and is my go to release for the rg35xx+!

**Comment by DutchmanAZ** [comment]
Check out batocera.org if you haven't already for some tips and tricks. 

You can access the RA menu by hitting the hotkey and the south button to adjust per game or per core configs. Some things can be adjusted in the ES menus by hitting select while in a Games list or holding the south button rather than tapping it when launching a game.

**Comment by DutchmanAZ** [comment]
Save states only work with RA Libretro cores. Are you sure it is using one of those when it doesn't work?

Save states seem to be working fine for me when I press the hotkey and Y. Load with hotkey and x

**Comment by Teh-Ghost** [comment]
The save state functionality within retroarch is working. However, the save state manager within batocera does not appear to be working.

**Comment by A-Bony-Mouse** [comment]
As Teh-Ghost said, in Batocera there is the option to open a save state manager before starting the game. Unfortunately even when there are save states, the save state manager does not see them. Maybe the save state manager is pointed at a different directory to what retroarch is using? As DutchmanAZ mentioned, I can save and load save states within a game using the hotkeys. And the retroarch menu also lets you change slots save and load. The auto-load save state also worked after I manually loaded the save state once.

**Comment by acmeplus** [comment]
Yeah, save state manager is currently broken, I need to investigate what's happening.

**Comment by Teh-Ghost** [comment]
This looks to potentially be fixed in the latest “Batocera v40 Beta for RG35XX Plus and RG35XX H - 20240306” release. I’ll continue testing a bit to see if the assumption is correct.  Thank you acmeplus for all of your work on this!

**Comment by Teh-Ghost** [comment]
Oops…accidentally closed the issue with previous comment…reopening until testing is done.

**Comment by rooster85** [comment]
Save state manager works for me on latest V40 beta, for existing save states you need to move them up one level in the folder structure (e.g. from saves/nes/fceumm to saves/nes) and they will show up correctly. New save states get created in the emulator save folder already which is also a new change in V40.
