### ISSUE TITLE
Gamecube support

### ISSUE THREAD

**Issue by evanmoran** [rg35xx-cfw/rg35xx-cfw.github.io#153]
Does gamecube work on this? When I add a game to a `gamecube` dir doesn't seem to add them to the games list. 

(Thanks for all your help. This work is amazing :)

**Comment by acmeplus** [comment]
You cannot expect GameCube to work on this console (or similar ones in terms of specs).

**Comment by evanmoran** [comment]
Thank you, much appreciated!
