### ISSUE TITLE
retroarch cannot access /mnt/sdcard/

### ISSUE THREAD

**Issue by grgohr** [rg35xx-cfw/rg35xx-cfw.github.io#16]
cannot browse the roms folder from retroarch (tried both fat32 and ntfs), nothing visible after /mnt/sdcard/
roms and systems are properly recognized by batocera though (/mnt/sdcard/roms/ and /mnt/sdcard/bios/)

**Comment by acmeplus** [comment]
> cannot browse the roms folder from retroarch (tried both fat32 and ntfs), nothing visible after /mnt/sdcard/
> roms and systems are properly recognized by batocera though (/mnt/sdcard/roms/ and /mnt/sdcard/bios/)

Newer versions of v0.2 & v0.3 don't use /mnt/sdcard for the cards but instead the cards are mounted in /userdata. That folder is actually the same regardless of whether you use internal storage from the first SDcard or second SDcard.

You can select the default storage in Settings -> System Settings -> Storage, and select internal or external partition. After that you need to restart for the changes to take place.
