### ISSUE TITLE
using 2 SD cards

### ISSUE THREAD

**Issue by supadubz** [rg35xx-cfw/rg35xx-cfw.github.io#164]
i have tried so much. and i cannot get my 2nd card, either formatted correctly nor recognized by the rg35xx plus. 
not a single concise tut on how to correctly format and add roms to the created folder. 
no information on what to click. the format option for card does not help the system recognize card. always end up with the default roms on the CFW

**Comment by acmeplus** [comment]
Duplicate, see #158
