### ISSUE TITLE
Retroachievement not connecting

### ISSUE THREAD

**Issue by MaxAndre1102** [rg35xx-cfw/rg35xx-cfw.github.io#167]
I tried to connect to the Retroachievement and I could get the trophies I have, however when I try to connect to a new game, there is a error message saying saying that there is a issue with the username or password. Is that happening to someone else?

**Comment by acmeplus** [comment]
Please give it a try with the latest firmware, there are a lot of changes and that may have been fixed in upstream.

**Comment by MaxAndre1102** [comment]
> Please give it a try with the latest firmware, there are a lot of changes and that may have been fixed in upstream.

I tried the 20240207 version and didnt work. I could download my achievements from previous systems but when I try to connect to a new game says that there is an issue to connect.

**Comment by MaxAndre1102** [comment]
Issue fixed. I created a new account and was able to connect. something wrong with my old account.
