### ISSUE TITLE
Select and Start buttons not working.

### ISSUE THREAD

**Issue by G7200** [rg35xx-cfw/rg35xx-cfw.github.io#17]
I cannot use Start and Select buttons on "batocera_lite_rg35xx_20230324_r3". How can the background music be switched off?

**Comment by acmeplus** [comment]
> I cannot use Start and Select buttons on "batocera_lite_rg35xx_20230324_r3". 

There's an issue with the newest versions of the RG35XX that has different key mappings for those keys. This will be fixed in the next release. 

> How can the background music be switched off?

In EmulationStation, Settings, Sound, turn off.

**Comment by G7200** [comment]
Good to know, thanks!

**Comment by acmeplus** [comment]
Closing this issue, fixed in v0.4
