### ISSUE TITLE
RA menu not currently accessible 

### ISSUE THREAD

**Issue by neocvera** [rg35xx-cfw/rg35xx-cfw.github.io#19]
I have not found a button combination that enters RA menu during gameplay. Although I have found the following: 

menu+A = restart game
menu+X = load
menu+Y= save
menu+start = exit to ES / menu+B = exit to ES / menu + L1 = exit to ES
menu+up = select save slot (increase #)
menu+down = select save slot (decrease #)
menu+(hold)right = FF (fast forward)

**Comment by acmeplus** [comment]
Yes, it's an issue because v0.4 has an issue with GL content (incorrect compilation that I need to fix). As a workaround, set the retroarch menu to RGUI: In EmulationStation go to ``Settings -> system settings -> Frontend Developer Options -> Retroarch Menu Drive -> RGUI``

**Comment by neocvera** [comment]
Thank you, yes - your workaround confirmed working. 
![IMAGE 2023-04-10 23:10:17](https://user-images.githubusercontent.com/67931174/231054026-eb0605bc-98ed-48e0-a774-2803c8339510.jpg)

**Comment by acmeplus** [comment]
Fixed in v0.5

**Comment by acmeplus** [comment]
> Hello,
> Just tested the v0.5 and the RA menu seems not available with N64 games.
> But works ok with other systems, thank you.

Some standalone emulators don't have working menus. But the main issue was in RA and it's now fixed.

**Comment by acmeplus** [comment]
Closing issue, fixed in v0.5
