### ISSUE TITLE
N64 - glitched Retroarch - RG35XX H - Batocera v40 Beta (20240306)

### ISSUE THREAD

**Issue by saperos** [rg35xx-cfw/rg35xx-cfw.github.io#197]
Hey everyone,

First off, huge thanks for putting the effort into creating this CFW - it's really awesome!

Just got my hands on a 35XXH and dove straight into some N64 games. Was eager to chase retroachievements on Paper Mario and Super Mario 64. But hit a snag: the core supporting Retroachievements and Retroarch (Libreto:Mupen64Plus-Next) seems to be giving me grief. When I open Retroarch with Func + B, all I get is this massive green rectangle. The overlay text (like logging into retroachievements popup) is also glitched - looks like a rainbowy rectangle.

Not sure if I'm messing something up or if it's a known issue with this release

**Comment by acmeplus** [comment]
Try to change the video_driver for retroarch to sdl2 instead of gl or glcore. You can define that by editing ``system/batocera.conf`` and adding a line at the end with:
```console
global.retroarch.video_driver = "sdl2"
```

**Comment by saperos** [comment]
> Try to change the video_driver for retroarch to sdl2 instead of gl or glcore. You can define that by editing `system/batocera.conf` and adding a line at the end with:
> 
> ```
> global.retroarch.video_driver = "sdl2"
> ```

Thank you for replying! Unfortunately, the problem persists.

**Comment by saperos** [comment]
I started messing around with this setting, and setting it to GL solved the issue :D

**Comment by acmeplus** [comment]
Try with one of the other possible values, ``gl`` and ``glcore``

**Comment by saperos** [comment]
Huge thanks to you kind stranger! Hope you will have a fantastic day!

**Comment by saperos** [comment]
Note to development team: it would be great to address this issue, as changing any display setting of the game, adds below line to config, which brakes RetroArch:

global.retroarch.video_driver = "sdl2"

**Comment by rooster85** [comment]
@saperos this kind stranger is the main dev of this Batocera cfw, lol

**Comment by saperos** [comment]
Oups! I did not know, I am very new to the community. :)

**Comment by paronowitz** [comment]
> ment team: it would be great to address this issue, as changing any display setting of the game, adds below line to config, which brakes RetroArch:
> 
> global.retroarch.video_driver = "sdl2"

To be clear use "gl" lowercase. Uppercase did not work

**Comment by paronowitz** [comment]
> I started messing around with this setting, and setting it to GL solved the issue :D

global.retroarch.video_driver = "gl"... lowercase GL did not work

**Comment by acmeplus** [comment]
Closing this issue since ``global.retroarch.video_driver = "gl"`` works
