### ISSUE TITLE
WiFi: batch scraping causing system refresh

### ISSUE THREAD

**Issue by neocvera** [rg35xx-cfw/rg35xx-cfw.github.io#20]
After adding games to a mame folder, attempted to scrape for game metadata/ images. 
Start-scraper-scrape now
Current result: batocera refreshes itself 
Expected behavior: downloading media for games missing media 

*scraping for individual games works
Highlight game, press and hold B, Scrape

**Comment by acmeplus** [comment]
The issue happens to with usb ethernet, not just tied to wifi.

**Comment by acmeplus** [comment]
Fixed in v0.7, closing issue
