### ISSUE TITLE
Sega Pico

### ISSUE THREAD

**Issue by Sp33dFr34k** [rg35xx-cfw/rg35xx-cfw.github.io#210]
There is a Sega Pico folder and I can scrape for it, but it doesn't show up at all, there's no emulator for it?

The games do show up in the All Games collection however.

Using Batocera V40 and RG35XX H.

**Comment by probe0580** [comment]
Rom Folder = pico8
File Extension = .p8 (not zip)

**Comment by Sp33dFr34k** [comment]
> Rom Folder = pico8 File Extension = .p8 (not zip)

Sega Pico != Pico 8 :)

From the pico folder's _info.txt:

> ## SYSTEM SEGA PICO ##
-------------------------------------------------------------------------------
ROM files extensions accepted: ".bin .md .zip .7z"

The folder I use is pico, and the extensions are .zip. Within the .zip there are .md files. The games run fine via the All Games collection as mentioned above, so I think this must be something simple.

**Comment by uzumak11** [comment]
Sega pico is not mentioned as one of the supported systems under release notes ("Cores/Emulators status")

The folders are populated/created cos that's how batocera(main) builds it

**Comment by Sp33dFr34k** [comment]
> Sega pico is not mentioned as one of the supported systems under release notes ("Cores/Emulators status")
> 
> The folders are populated/created cos that's how batocera(main) builds it

Ah okay, didn't check that. Thanks. The emulator seems to be there though as the games work. But I'll close it then as it's not a bug.
