### ISSUE TITLE
Stuck on Boot Splash Screen Logo

### ISSUE THREAD

**Issue by EdwardTheBanker** [rg35xx-cfw/rg35xx-cfw.github.io#23]
Hi i already tried burning with 2 micro sd one with 128gb and another with 256gb using Rufus, Balena Etche and Win32Diskimager but no success.
i don't know which version im at just that the battery capacity is 2600mah.
Stock micro sd works fine btw.
I tried Batocera 0.4 and 0.5.

**Comment by acmeplus** [comment]
Have you tried garlic. If so which version(s) and which one works for you?

**Comment by EdwardTheBanker** [comment]
> Have you tried garlic. If so which version(s) and which one works for you?

I haven't tried any cfw besides batocera, but i will try rn.

**Comment by EdwardTheBanker** [comment]
I just installed and got the same problem as batocera, stuck on boot splash screen logo.

**Comment by acmeplus** [comment]
> I just installed and got the same problem as batocera, stuck on boot splash screen logo.

try the latest garlic 1.4.6

**Comment by EdwardTheBanker** [comment]
I tried lastest Garlic and it booted 1st try...

**Comment by EdwardTheBanker** [comment]
it fixed it's working know, ty very much.

**Comment by EdwardTheBanker** [comment]
it's working now.

**Comment by Allexxo92** [comment]
@acmeplus its a new board on the rg35xx 6.0c

**Comment by qcai99jjk** [comment]
hi i think i got the same problem, i open the case & the board written as rg35xx_V6S  2023-06-07 . Please see the picture below. can you help me with boot issue, its just went blank with green light led 
![rg35xx](https://github.com/user-attachments/assets/8593fb78-6f4e-480f-98f2-359aaedb8b23)
