### ISSUE TITLE
Numerous cores' speed is faster than actual and no game sounds.

### ISSUE THREAD

**Issue by mdlarussa** [rg35xx-cfw/rg35xx-cfw.github.io#27]
Alpha 0.6 - FBNEO, NES, FDS, all play at about 1.25x normal speed, even though no overclocking is turned on.  

None of the cores are outputting sound during games.  Preview videos have sound, and the background music is playing, but I can't get sound in any core to play.  Noticed in cores I tried: FBNEO, NES/FDS, ColecoVision, Atari2600/7800.

**Comment by acmeplus** [comment]
You need to copy the file https://github.com/rg35xx-cfw/rg35xx-cfw.github.io/releases/download/rg35xx_batocera_lite_alpha_v0.5/batocera.conf to the system folder (either /userdata/system/batocera.conf or SHARE/system/batocera.conf)

If you have reformatted the internal partition or have added a second card, you need to copy that file to have the correct audio setup.
