### ISSUE TITLE
NeoGeo games do not load

### ISSUE THREAD

**Issue by facemasktuxedo** [rg35xx-cfw/rg35xx-cfw.github.io#28]
I placed neogeo.zip in both the bios folder as well as the roms/neogeo folder. The screen goes black on load then returns to the menu similar to the NDS issue others experienced.

**Comment by neocvera** [comment]
Could be your romset and compatibility with a particular core. I believe neogeo roms use fbneo by default (when using the ‘neogeo’ folder)

**Comment by acmeplus** [comment]
Closing this ticket, neogeo roms work without issues, even if neogeo.zip bios is not present.
