### ISSUE TITLE
Beta v0.7 select button not mapped ES Menu 

### ISSUE THREAD

**Issue by neocvera** [rg35xx-cfw/rg35xx-cfw.github.io#37]
Upon initial flashing of the image: 
Select should pull up the “quick access” menu in the ES screen. 

Currently scrolls selection right. 

Fix: perform remapping of buttons via ES “Controller & Bluetooth Settings/ Controller Mappings”

**Comment by acmeplus** [comment]
Most likely es_input.cfg is not correct. Will be fixed in the next release

**Comment by XQuader** [comment]
Odd, it pulls up "Quick Access" in my v0.7 installation...

**Comment by XQuader** [comment]
Collection scrolling using L1/R1 doesn't work too (R1 goes up, instead of down, L1 doesn't go down)

**Comment by acmeplus** [comment]
Have a look at the included es_input.cfg, then remap the keys using the menu, and compare the RG35XX gamepad section. I assume I mixed up the indexes for the buttons.

**Comment by acmeplus** [comment]
Fixed in v0.8. Closing
