### ISSUE TITLE
N64 emualtor performance

### ISSUE THREAD

**Issue by rogerillu** [rg35xx-cfw/rg35xx-cfw.github.io#47]
Hi,

N64 emulator with RICE core works better in version 0.6 than in the newer versions (0.7, 0.8, and 0.81).
I the last versions, sound is bad and sometimes it gets slow.

**Comment by acmeplus** [comment]
Yes, there are some performance issues with v0.8.1

**Comment by acmeplus** [comment]
Please check #45 for general performance issues, closing this issue.
