### ISSUE TITLE
Random button presses on V6C mainboard

### ISSUE THREAD

**Issue by Schaefers** [rg35xx-cfw/rg35xx-cfw.github.io#50]
I'm seeing random button presses on `37-dev`, my mainboard is `RG35XX_V6C 2023-01-30`. I'm using batocera on a SandDisk memory card. They're not occuring with the original OS on the bundled sd card. 

![IMG_6790](https://github.com/rg35xx-cfw/rg35xx-cfw.github.io/assets/9284160/be223ad8-34eb-4348-9e16-b6161d41dafd)

**Comment by Schaefers** [comment]
Apparently this has been a broken unit, got another one with the same mainboard and don't have random button presses there. Closing here.

**Comment by acmeplus** [comment]
> Apparently this has been a broken unit, got another one with the same mainboard and don't have random button presses there. Closing here.

Glad that it was resolved. There are some hardware variations even with the same revisions that make it very hard to determine what’s hardware or firmware related.
