### ISSUE TITLE
menu button not working

### ISSUE THREAD

**Issue by dooeif5** [rg35xx-cfw/rg35xx-cfw.github.io#51]
all buttons work except the menu so i cant save or exit games

**Comment by acmeplus** [comment]
Try to use an external keyboard and remap the controls in batocera. Alternatively you can delete the file system/configs/emulationstation/es_input.cfg and try again.

**Comment by descalzi** [comment]
Same, I tried deleting "es_input.cfg" using the app in Ports. Once I exit the app it automatically goes into the keys-mapping, which rg35xx-plus doesnt have analog-arrows .. so I rebooted but menu key still doesnt do anything

**Comment by acmeplus** [comment]
> Same, I tried deleting "es_input.cfg" using the app in Ports. Once I exit the app it automatically goes into the keys-mapping, which rg35xx-plus doesnt have analog-arrows .. so I rebooted but menu key still doesnt do anything

This is a very old ticket for the rg35xx during the development. It does not apply to the current firmware for the RG35XX or for the RG35XX plus.

What's the issue that you have? Note that in EmulationStation the Menu button is not mapped to menu but instead used as a hotkey. For instance Menu + START exits the emulator.
