### ISSUE TITLE
U-boot.

### ISSUE THREAD

**Issue by cxxr2** [rg35xx-cfw/rg35xx-cfw.github.io#59]
Where I can get source code for u-boot with specific configuration for rg35xx to standalone compile it.

**Comment by acmeplus** [comment]
the u-boot repo is here: https://github.com/rg35xx-cfw/u-boot_s500/tree/rg35xx

Note that boot is not used for koriki (it uses the boot binary) since there are elements that are not available in the open source version.

**Comment by cxxr2** [comment]
Thank you.
