### ISSUE TITLE
eduke3d

### ISSUE THREAD

**Issue by benchristey** [rg35xx-cfw/rg35xx-cfw.github.io#84]
I've not been able to get eduke32 to work - is this supported?

**Comment by garland410** [comment]
Don't want to overstate because my memory is crap and I'm pretty sure I only loaded the title screen back then to test, but I recall this working, at least up to that point a few updates ago.

**Comment by benchristey** [comment]
Hmm I was sure I followed the instructions but mine just goes to a black screen then returns to the menu. If you get a sec I’d appreciate you sharing your folder/file structure and the contents of your launcher file.

**Comment by acmeplus** [comment]
Just checked and there is a compilation issue with the eduke32 version included in the firmware, so that's why it's not working. It'll be updated in the next version

**Comment by benchristey** [comment]
Ah that explains it. Thanks!

**Comment by benchristey** [comment]
Its working on the latest release thanks!
