### ISSUE TITLE
Updated from 0119 to 0126 2nd SD Card Contol

### ISSUE THREAD

**Issue by McSmeecherson** [rg35xx-cfw/rg35xx-cfw.github.io#93]
Updated to latest 0126 and was hoping to use same 2nd SD card from 0119, however the controls in menu are totally broken, is there a config file I can fix or do I need to redo 2nd card

**Comment by acmeplus** [comment]
Move or rename the system folder on the second card. Then it will be recreated with the correct configuration the next time you boot.

**Comment by McSmeecherson** [comment]
That did the trick, thanks!
